---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: assetcache-exporter

before:
  hooks:
    - mise run tidy-check

builds:
  - id: assetcache_exporter
    main: ./cmd/assetcache_exporter
    binary: assetcache_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{ .Version }}
      - -X github.com/prometheus/common/version.Revision={{ .Commit }}
      - -X github.com/prometheus/common/version.Branch={{ .Branch }}
      - -X github.com/prometheus/common/version.BuildUser=goreleaser
      - -X github.com/prometheus/common/version.BuildDate={{ .Date }}
